### ISSUE TITLE
fastax FTP issue

### ISSUE THREAD

**Issue by Tao2020yes** [Picani/fastax#1] opened 2021-05-29 20:17 UTC
I tried to populate the taxon database using "fastax populate". It gives a message saying "fastax: FTP InvalidResponse: Expected code [227], got response: 501 PASV: Operation not permitted". Such that, the database was not successfully cloned. Could you give suggestions to address the issue? Thanks.

**Comment by Picani** [comment] 2021-05-31 07:54
Hi

Thanks for pointing this out!

Could you post the output of `fastax --debug populate` please?

Moreover, are you behind a proxy? If yes, it might be it blocking the FTP...

Thanks!

**Comment by Tao2020yes** [comment] 2021-06-01 00:39
<img width="758" alt="Screen Shot 2021-05-31 at 8 37 53 PM" src="https://user-images.githubusercontent.com/59539873/120251617-19be3480-c250-11eb-8cc5-5ee552906455.png">
I don't use a proxy. Thank you for your reponse.

**Comment by Picani** [comment] 2021-06-02 09:38
The `PASV: Operation not permitted` means that, for some reason, you cannot use the passive mode of FTP.

Could you try with a regular FTP client? Just to test if the problem is from fastax or from your network.

If the `ftp` command is available, you can try

    ftp -p ftp.ncbi.nih.gov/pub/taxonomy

Then, once you're connected, type the following in the prompt

    get taxdmp.zip

If the `ftp` command is not available, but the `lftp` command is available, you can try

    lftp ftp.ncbi.nih.gov/pub/taxonomy/

Then, once you're connected, type the following in the prompt

    set ftp:passive-mode true
    get taxdmp.zip

In the meantime, I'll try to update the ftp library to a more up-to-date one.

**Comment by Picani** [comment] 2021-06-20 15:55
Hi

I'm in the process of modernizing the database layer.

When done, it will be possible to populate the local database from a file or to let fastax downloads it from the NCBI servers. This should fix the current problem.

I'll close this issue at that time.

**Comment by Picani** [comment] 2023-03-19 19:06
Fixed in v1.5.0

**Closed as completed by Picani** 2023-03-19 19:06 UTC
